#!/usr/bin/env python3
# name André Graça


import os



# Function to generate directory structure

def generate_directory_structure(user_path):

    for root, dirs, files in os.walk(user_path):

        # Print the current directory

        print("==root==")

        print(root)

        # Print sub-directories

        print("==dirs==")

        for directory in dirs:

            print(os.path.join(root, directory))

        # Print files

        print("==files==")

        for file in files:

            print(os.path.join(root, file))

# Main

if __name__ == "__main__":

    # Read user input for the directory path

    user_path = input("Enter the directory path: ")

    if os.path.exists(user_path):

        generate_directory_structure(user_path)

    else:

        print("The provided directory path does not ex>


