#!/usr/bin/env python3
# name André Graça

#Assign a list of ten string elements to a variable.

my_list = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

# Print the fourth element of the list.

print("4:", my_list[3])

# Print the sixth through tenth element of the list.

print("6 to 10 :", my_list[5:10])


# Change the value of the seventh element to "onion".

my_list[6] = "onion"


# Print the updated list.

print("Updated List:", my_list)

